apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aas-too
spec:
  ingressClassName: nginx-red
  rules:
  - host: aas-too.local
    http:
      paths:
      - backend:
          serviceName: aas-too-svc
          servicePort: 80
  tls:
  - hosts:
    - aas-too.local