apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aas-tools
  # annotations:
  #     kubernetes.io/ingress.class: nginx-red-internal
spec:
  ingressClassName: nginx-red-internal
  rules:
  - host: application.itv.local.url
    http:
      paths:
      - backend:
          serviceName: aas-tools-svc
          servicePort: 80
  tls:
  - hosts:
    - application.itv.local.url 